config/routes.rb
Secretconfessions::Application.routes.draw do

  resources :confessions
  
  root :to => 'confessions#index'
  
  get 'calling' => 'calling#index'
  
  post 'calling/incomingCall' => 'calling#incomingCall'
  post 'calling/recording' => 'calling#recording'
 
end

app/models/confession.rb
class Confession < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calling_controller.rb
class CallingController < ApplicationController    
  
  def incomingCall  
    # r = Twilio::REST::Response.new
    
    render :action => 'response.xml', :layout => false
  end
  
  def recording
    puts "I am in RECORDING!!!"
    
    incomingPhoneNumber = params[:From]          
    incomingAreaCode = incomingPhoneNumber.slice(2,3)
    recording_url = params[:RecordingUrl].to_s
    
    @confession.create!(:area_code => incomingAreaCode, :recording_url => recording_url)
    
    render :xml => "<success/>"
  end
end

app/controllers/confessions_controller.rb
class ConfessionsController < ApplicationController
  # GET /confessions
  # GET /confessions.json
  def index
    @confessions = Confession.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @confessions }
    end
  end

  # GET /confessions/1
  # GET /confessions/1.json
  def show
    @confession = Confession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @confession }
    end
  end

  # GET /confessions/new
  # GET /confessions/new.json
  def new
    @confession = Confession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @confession }
    end
  end

  # GET /confessions/1/edit
  def edit
    @confession = Confession.find(params[:id])
  end

  # POST /confessions
  # POST /confessions.json
  def create
    @confession = Confession.new(params[:confession])

    respond_to do |format|
      if @confession.save
        format.html { redirect_to @confession, notice: 'Confession was successfully created.' }
        format.json { render json: @confession, status: :created, location: @confession }
      else
        format.html { render action: "new" }
        format.json { render json: @confession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /confessions/1
  # PUT /confessions/1.json
  def update
    @confession = Confession.find(params[:id])

    respond_to do |format|
      if @confession.update_attributes(params[:confession])
        format.html { redirect_to @confession, notice: 'Confession was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @confession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /confessions/1
  # DELETE /confessions/1.json
  def destroy
    @confession = Confession.find(params[:id])
    @confession.destroy

    respond_to do |format|
      format.html { redirect_to confessions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calling_helper.rb
module CallingHelper
end

app/helpers/confessions_helper.rb
module ConfessionsHelper
end

app/views/calling/index.html.haml
Calling View

app/views/confessions/_form.html.haml
= form_for @confession, :html => { :class => 'form-horizontal' } do |f|
  -if @confession.errors.any?
    #error_explanation
      %h2= "#{pluralize(@confession.errors.count, "error")} prohibited this confession from being saved:"
      %ul
        - @confession.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend
      = controller.action_name.capitalize
      Confession
    .control-group
      = f.label :areacode, :class => 'control-label'
      .controls
        = f.text_field :areacode, :class => 'text_field'
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', confessions_path, :class => 'btn'

app/views/confessions/edit.html.haml
%h1 Editing confession

= render 'form'

= link_to 'Show', @confession
\|
= link_to 'Back', confessions_path

app/views/confessions/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Areacode
      %th Recording
      %th Confessed At
      %th
  %tbody
    - @confessions.each do |confession|
      %tr
        %td= link_to confession.areacode, confession
        %td= confession.recording_url
        %td= confession.created_at
        %td
          = link_to 'Edit', edit_confession_path(confession), :class => 'btn btn-mini'
          = link_to 'Destroy', confession, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger'
%br

= link_to 'New Confession', new_confession_path, :class => 'btn btn-primary'

app/views/confessions/new.html.haml
%h1 New confession

= render 'form'

= link_to 'Back', confessions_path

app/views/confessions/show.html.haml
%p#notice= notice

%p
  %b Areacode:
  = @confession.areacode

= link_to 'Edit', edit_confession_path(@confession)
\|
= link_to 'Back', confessions_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Secret Confessions
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} Secret Confessions
          .nav-collapse
            %ul.nav.pull-left
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Sort by
                  %b.caret
                %ul.dropdown-menu
                  %li
                    %a{:href => "#"} Action
                  %li
                    %a{:href => "#"} Another action
                  %li
                    %a{:href => "#"} Something else here
                  %li.divider
                  %li.nav-header Nav header
                  %li
                    %a{:href => "#"} Separated link
                  %li
                    %a{:href => "#"} One more separated link
            %ul.nav.pull-right
              %li
                %h2="Ready to leave yours? (424) 275-2362"
    #headimg
    #sentence
      Call in to leave an anonymous confession of your own!
    .container
      = yield